name: Clone Repo via IAM + SSM

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::339713188167:role/role1
          aws-region: us-east-1

      - name: Debug AWS Identity
        run: aws sts get-caller-identity

      - name: Clone Repo on EC2
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-0508584264047e7ff" \
            --parameters commands='[
              "cd /home/ec2-user || exit",
              "rm -rf MultiHubApp || true",
              "git clone https://github.com/pundlamahesh/MultiHubApp.git"
            ]'
